simple env variable solution
vshn/appcat-apiserver pull request #11
Opened 2023-03-12 11:55 UTC by wejdross

## Summary

* Short summary of what's included in the PR
* Give special note to breaking changes

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Update tests.
- [ ] Link this PR to related issues.

2023-03-13 10:54 UTC, zugao reviewed
It would be good to have these parameters explained via `appcat-apiserver --help`. Also they have to be explained in docs as well.

2023-03-13 10:54 UTC, zugao commented on main.go
> +	if os.Getenv("APPCAT_ENABLED") == "1" {
```suggestion
	if os.Getenv("APPCAT_HANDLER_ENABLED") == "1" {
```

I would change a bit the name to be more explicit.

2023-03-13 10:54 UTC, zugao commented on main.go
> +	if os.Getenv("VSHN_ENABLED") == "1" {
```suggestion
	if os.Getenv("VSHN_POSTGRES_BACKUP_HANDLER_ENABLED") == "1" {
```

I would not create an aggregate group just now. Let's go with more refined enabling system.

2023-03-13 10:54 UTC, zugao commented on config/aggregated-apiserver.yaml
> +          env:
I would add all env variables in a config map.

2023-03-15 07:56 UTC, glrf reviewed
Could you also add a few words about the environment variables in the README or so? Otherwise the only way to figure out what envVars you can set is by reading the code

2023-03-15 07:56 UTC, glrf commented on main.go
> +	if os.Getenv("APPCAT_HANDLER_ENABLED") == "1" {
Nitpick: I'd default to `true` for enabling the appcat API handler

2023-03-15 07:56 UTC, glrf commented on main.go
> +	}
```suggestion
    vshnEnabled, err = strconv.ParseBool(os.Getenv("VSHN_POSTGRES_BACKUP_HANDLER_ENABLED"))
	if err != nil {
	    klog.Printf("Failed to parse VSHN_POSTGRES_BACKUP_HANDLER_ENABLED: %s", err.Error())
		vshnEnabled = false
	}
```

I'd suggest using `ParseBool` to set the environment variable. That way `true` or `True` or `TRUE` or `T` all still work.

2023-03-15 07:56 UTC, glrf commented on main.go
> +		log.Fatal(err)
Please use `klog` if we already have it

2023-03-15 10:12 UTC, glrf commented on main.go
> +	if os.Getenv("APPCAT_HANDLER_ENABLED") != "" {
You don't need this check anymore. If it's `""` `PraseBool` will just return an error.

2023-03-21 10:19 UTC, Kidswiss requested changes
Just the usual: the summary in the PR is empty :)

2023-03-21 10:19 UTC, Kidswiss commented on main.go
> +	vshnEnabled, err = strconv.ParseBool(os.Getenv("VSHN_POSTGRES_BACKUP_HANDLER_ENABLED"))
Nitpick: the variable name could be a bit confusing, as it doesn't contain `backup` and enables the backuphandler.

2023-03-21 13:52 UTC, glrf approved these changes

2023-03-22 10:07 UTC, zugao approved these changes
Haven't checked on a real cluster but the code looks good to me.

2023-03-28 06:32 UTC, merged